### ISSUE TITLE
Error in get_true_argspec when class based decorator uses context manager with certain Python versions

### ISSUE THREAD

**Issue by dgilland** [apiguy/flask-classy#56]
This is a strange bug that seems to affect only certain versions of Python 2.7.3 depending on the GCC version used (maybe?). It's due to the ordering of [method.__closure__](https://github.com/apiguy/flask-classy/blob/master/flask_classy.py#L306) which, when not "right", causes a `TypeError: <...object...> is not a Python function` error when [argspec = inspect.getargspec(method)](https://github.com/apiguy/flask-classy/blob/master/flask_classy.py#L297) is called while processing the [closure](https://github.com/apiguy/flask-classy/blob/master/flask_classy.py#L307).

From my testing, the following Python version **did not** have this issue:

```
$ python -c 'import sys; print(sys.version)'
2.7.3 (default, Feb 27 2014, 19:37:34) 
[GCC 4.7.2]
```

While this version **did**:

```
$ python -c 'import sys; print(sys.version)'
2.7.3 (default, Feb 27 2014, 19:58:35) 
[GCC 4.6.3]
```

My test code which is using Flask-Classy v0.6.8:

``` python
from functools import wraps

from flask import Flask
from flask.ext.classy import FlaskView

app = Flask(__name__)

class Decorator(object):
    def __init__(self, x=True):
        self.x = x

    def __call__(self, f):
        @wraps(f)
        def decorated(*args, **kargs):
            with self:
                rv = f(*args, **kargs)
            return rv
        return decorated

    def __enter__(self):
        if self.x is False:
            raise Exception

    def __exit__(self, *args):
        return False

class TestView(FlaskView):
    @Decorator()
    def index(self):
        return "Hello World!"

if __name__ == "__main__":
    TestView.register(app)
    with app.test_client() as client:
        print client.get('/test/').data
```

When run on the "bad" Python version, the traceback is:

```
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    TestView.register(app)
  File "/home/dgilland/projects/testing/flask-classy-bug/env/local/lib/python2.7/site-packages/flask_classy.py", line 144, in register
    rule = cls.build_rule("/", value)
  File "/home/dgilland/projects/testing/flask-classy-bug/env/local/lib/python2.7/site-packages/flask_classy.py", line 260, in build_rule
    args = get_true_argspec(method)[0]
  File "/home/dgilland/projects/testing/flask-classy-bug/env/local/lib/python2.7/site-packages/flask_classy.py", line 332, in get_true_argspec
    true_argspec = get_true_argspec(inner_method)
  File "/home/dgilland/projects/testing/flask-classy-bug/env/local/lib/python2.7/site-packages/flask_classy.py", line 313, in get_true_argspec
    argspec = inspect.getargspec(method)
  File "/usr/lib/python2.7/inspect.py", line 815, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <__main__.Decorator object at 0x2110250> is not a Python function
```

The order of `method.__closure__` on the **good** version is:

``` python
(<cell at 0x16f9ec0: function object at 0x17007d0>, <cell at 0x16f97c0: Decorator object at 0x16fc950>)
```

While the order on the **bad** version is reversed:

``` python
(<cell at 0x20db670: Decorator object at 0x2110250>, <cell at 0x20dbe88: function object at 0x20dd8c0>)
```

So the issue is that the `function object` comes after the `Decorator object` which results in the wrong function being passed to `get_true_argspec` in the `for cell in closure` loop.

I really don't know enough about how/why Python is ordering the `method.__closure__` object differently between versions but a workaround that I've implemented which seems to bypass this situation (but may not be correct?) is this:

``` python
closure = method.__closure__
for cell in closure:
    inner_method = cell.cell_contents
    # @patch: skip inner_method if it's not a function
    if inner_method is method or not inspect.isfunction(inner_method):
        continue
    true_argspec = get_true_argspec(inner_method)
    if true_argspec:
        return true_argspec
```

I've added `or not inspect.isfunction(inner_method)` to `if inner_method is method` which skips any `cell` objects which are not functions.

**Comment by dgilland** [comment]
This has been fixed in [v0.6.10](https://pypi.python.org/pypi/Flask-Classy/0.6.10). Thanks so much @apiguy :+1:
